# Generated by Django 4.1.7 on 2023-05-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobcategory_jobstatus_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='coverLetter',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
