# Generated by Django 4.1.4 on 2023-05-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_job_coverletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
