# Generated by Django 4.1.4 on 2023-05-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_job_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="text_content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
