# Generated by Django 4.1.4 on 2023-05-12 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_job_text_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="coverLetter",
        ),
    ]
