# Generated by Django 4.1.4 on 2023-05-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_job_coverletter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="text_content",
            new_name="job_description",
        ),
        migrations.RemoveField(
            model_name="job",
            name="description",
        ),
        migrations.AddField(
            model_name="job",
            name="resume_text",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
