# Generated by Django 4.1.4 on 2023-05-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_rename_text_content_job_job_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cover_letter",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
