# Generated by Django 4.1.4 on 2023-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_job_cover_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="matching_score",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="suggested_keywords",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
