# Generated by Django 4.1.4 on 2023-05-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_job_matching_score_job_suggested_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="matching_score",
            field=models.FloatField(default=0.0),
        ),
    ]
